DELETE FROM DESCRIPTION;
DELETE FROM DIFFICULTY;
DELETE FROM MAINOBJECTIVE;

ALTER TABLE DESCRIPTION AUTO_INCREMENT = 1;
ALTER TABLE DIFFICULTY AUTO_INCREMENT = 1;
ALTER TABLE MAINOBJECTIVE AUTO_INCREMENT = 1;